import productImage from "@/assets/product-terracotta-vase.jpg";
import categoryRoti from "@/assets/category-roti.jpg";
import categoryKapda from "@/assets/category-kapda.jpg";
import categoryMakan from "@/assets/category-makan.jpg";

export const categories = [
  { id: "all", label: "All Products" },
  { id: "roti", label: "Roti (Wellness)" },
  { id: "kapda", label: "Kapda (Textiles)" },
  { id: "makan", label: "Makan (Home)" },
];

export const mockProducts = [
  {
    id: "1",
    name: "Handcrafted Terracotta Vase",
    subtitle: "Traditional Rajasthani Pottery",
    category: "makan",
    price: 2499,
    originalPrice: 2999,
    image: productImage,
    images: [productImage, productImage, productImage],
    description: "This exquisite terracotta vase is handcrafted by skilled artisans in Rajasthan using traditional techniques passed down through generations.",
    features: [
      "100% natural terracotta clay",
      "Hand-carved traditional patterns",
      "Food-safe finish",
      "Suitable for fresh or dried flowers",
    ],
    stockCount: 12,
  },
  {
    id: "2",
    name: "Organic Turmeric & Honey Set",
    subtitle: "Pure Natural Ingredients",
    category: "roti",
    price: 899,
    originalPrice: null,
    image: categoryRoti,
    images: [categoryRoti, categoryRoti, categoryRoti],
    description: "Organic turmeric and honey blend for natural wellness and immune support.",
    features: [
      "100% organic turmeric",
      "Pure raw honey",
      "No additives",
      "Naturally sourced",
    ],
    stockCount: 25,
  },
  {
    id: "3",
    name: "Block-Printed Cotton Stole",
    subtitle: "Handwoven Traditional Design",
    category: "kapda",
    price: 1499,
    originalPrice: 1799,
    image: categoryKapda,
    images: [categoryKapda, categoryKapda, categoryKapda],
    description: "Beautiful block-printed cotton stole featuring traditional patterns.",
    features: [
      "100% cotton",
      "Hand block-printed",
      "Traditional design",
      "Lightweight and breathable",
    ],
    stockCount: 18,
  },
  {
    id: "4",
    name: "Brass Diya Set (Pack of 5)",
    subtitle: "Traditional Decorative Diyas",
    category: "makan",
    price: 1299,
    originalPrice: null,
    image: categoryMakan,
    images: [categoryMakan, categoryMakan, categoryMakan],
    description: "Set of 5 beautifully crafted brass diyas perfect for festivals and décor.",
    features: [
      "Pure brass",
      "Traditional design",
      "Pack of 5",
      "Oil lamp ready",
    ],
    stockCount: 30,
  },
  {
    id: "5",
    name: "Khadi Cotton Kurta",
    subtitle: "Comfortable Traditional Wear",
    category: "kapda",
    price: 2199,
    originalPrice: 2599,
    image: categoryKapda,
    images: [categoryKapda, categoryKapda, categoryKapda],
    description: "Handwoven khadi cotton kurta with traditional craftsmanship.",
    features: [
      "100% khadi cotton",
      "Handwoven",
      "Breathable",
      "Perfect for all seasons",
    ],
    stockCount: 15,
  },
  {
    id: "6",
    name: "Pure Himalayan Honey (500g)",
    subtitle: "Raw & Unfiltered",
    category: "roti",
    price: 649,
    originalPrice: null,
    image: categoryRoti,
    images: [categoryRoti, categoryRoti, categoryRoti],
    description: "Pure raw Himalayan honey collected from high-altitude apiaries.",
    features: [
      "100% pure honey",
      "Raw and unfiltered",
      "Himalayan sourced",
      "No additives",
    ],
    stockCount: 40,
  },
  {
    id: "7",
    name: "Stoneware Dinner Plate Set",
    subtitle: "Elegant Dining Collection",
    category: "makan",
    price: 2799,
    originalPrice: 3299,
    image: categoryMakan,
    images: [categoryMakan, categoryMakan, categoryMakan],
    description: "Handcrafted stoneware dinner plates with elegant finish.",
    features: [
      "Artisan stoneware",
      "Dishwasher safe",
      "Set of 4",
      "Food-safe glazing",
    ],
    stockCount: 12,
  },
  {
    id: "8",
    name: "Organic Cold-Pressed Mustard Oil",
    subtitle: "Pure & Natural",
    category: "roti",
    price: 599,
    originalPrice: 699,
    image: categoryRoti,
    images: [categoryRoti, categoryRoti, categoryRoti],
    description: "Cold-pressed mustard oil extracted using traditional methods.",
    features: [
      "Cold-pressed",
      "100% organic",
      "No chemicals",
      "Rich in antioxidants",
    ],
    stockCount: 35,
  },
  {
    id: "9",
    name: "Handloom Cotton Bedsheet",
    subtitle: "Soft & Durable",
    category: "kapda",
    price: 1899,
    originalPrice: 2299,
    image: categoryKapda,
    images: [categoryKapda, categoryKapda, categoryKapda],
    description: "Premium handloom cotton bedsheet for comfortable sleep.",
    features: [
      "100% cotton",
      "Handwoven",
      "Soft and breathable",
      "Double bed size",
    ],
    stockCount: 20,
  },
  {
    id: "10",
    name: "Terracotta Water Bottle",
    subtitle: "Natural Cooling Properties",
    category: "roti",
    price: 899,
    originalPrice: null,
    image: categoryRoti,
    images: [categoryRoti, categoryRoti, categoryRoti],
    description: "Eco-friendly terracotta water bottle with natural cooling effect.",
    features: [
      "Pure terracotta",
      "Natural cooling",
      "Eco-friendly",
      "1 liter capacity",
    ],
    stockCount: 22,
  },
  {
    id: "11",
    name: "Jute Storage Basket",
    subtitle: "Eco-Friendly Organization",
    category: "makan",
    price: 1199,
    originalPrice: 1499,
    image: categoryMakan,
    images: [categoryMakan, categoryMakan, categoryMakan],
    description: "Natural jute storage basket for organizing your home.",
    features: [
      "100% jute",
      "Eco-friendly",
      "Durable weave",
      "Multiple sizes",
    ],
    stockCount: 28,
  },
  {
    id: "12",
    name: "Naturally Dyed Cotton Dupatta",
    subtitle: "Traditional Colors",
    category: "kapda",
    price: 1299,
    originalPrice: 1599,
    image: categoryKapda,
    images: [categoryKapda, categoryKapda, categoryKapda],
    description: "Cotton dupatta dyed with natural plant-based colors.",
    features: [
      "Naturally dyed",
      "100% cotton",
      "Traditional patterns",
      "Breathable fabric",
    ],
    stockCount: 16,
  },
  {
    id: "13",
    name: "Organic Herbal Tea Blend",
    subtitle: "Wellness in a Cup",
    category: "roti",
    price: 499,
    originalPrice: null,
    image: categoryRoti,
    images: [categoryRoti, categoryRoti, categoryRoti],
    description: "Blend of organic herbs for daily wellness and relaxation.",
    features: [
      "100% organic herbs",
      "Caffeine-free",
      "No preservatives",
      "50g pack",
    ],
    stockCount: 45,
  },
  {
    id: "14",
    name: "Hand-Carved Wooden Tray",
    subtitle: "Artisan Craftsmanship",
    category: "makan",
    price: 1999,
    originalPrice: 2399,
    image: categoryMakan,
    images: [categoryMakan, categoryMakan, categoryMakan],
    description: "Beautifully hand-carved wooden serving tray.",
    features: [
      "Solid wood",
      "Hand-carved",
      "Food-safe finish",
      "Durable design",
    ],
    stockCount: 14,
  },
  {
    id: "15",
    name: "Khadi Cushion Cover Set",
    subtitle: "Comfort & Style",
    category: "kapda",
    price: 999,
    originalPrice: 1299,
    image: categoryKapda,
    images: [categoryKapda, categoryKapda, categoryKapda],
    description: "Soft khadi cotton cushion covers for your home décor.",
    features: [
      "100% khadi cotton",
      "Set of 2",
      "Handwoven",
      "Easy to clean",
    ],
    stockCount: 24,
  },
  {
    id: "16",
    name: "A2 Desi Cow Ghee (500ml)",
    subtitle: "Pure & Nutritious",
    category: "roti",
    price: 1599,
    originalPrice: 1799,
    image: categoryRoti,
    images: [categoryRoti, categoryRoti, categoryRoti],
    description: "Pure A2 ghee from desi cows with traditional preparation.",
    features: [
      "A2 cow ghee",
      "No additives",
      "Traditional method",
      "Rich in nutrients",
    ],
    stockCount: 18,
  },
  {
    id: "17",
    name: "Brass Incense Holder",
    subtitle: "Decorative & Functional",
    category: "makan",
    price: 899,
    originalPrice: null,
    image: categoryMakan,
    images: [categoryMakan, categoryMakan, categoryMakan],
    description: "Elegant brass incense holder for aromatherapy.",
    features: [
      "Pure brass",
      "Hand-finished",
      "Traditional design",
      "Compact size",
    ],
    stockCount: 26,
  },
  {
    id: "18",
    name: "Handwoven Cotton Scarf",
    subtitle: "Versatile Fashion",
    category: "kapda",
    price: 1099,
    originalPrice: 1399,
    image: categoryKapda,
    images: [categoryKapda, categoryKapda, categoryKapda],
    description: "Lightweight handwoven cotton scarf perfect for all seasons.",
    features: [
      "100% cotton",
      "Handwoven",
      "Lightweight",
      "Versatile styling",
    ],
    stockCount: 20,
  },
  {
    id: "19",
    name: "Organic Jaggery Powder",
    subtitle: "Natural Sweetener",
    category: "roti",
    price: 349,
    originalPrice: null,
    image: categoryRoti,
    images: [categoryRoti, categoryRoti, categoryRoti],
    description: "Pure organic jaggery powder from sugarcane.",
    features: [
      "100% organic",
      "No chemicals",
      "Natural sweetness",
      "250g pack",
    ],
    stockCount: 50,
  },
  {
    id: "20",
    name: "Clay Cooking Pot with Lid",
    subtitle: "Traditional Cooking",
    category: "makan",
    price: 1899,
    originalPrice: 2199,
    image: categoryMakan,
    images: [categoryMakan, categoryMakan, categoryMakan],
    description: "Handmade clay cooking pot for healthy and authentic cooking.",
    features: [
      "Pure clay",
      "Food-safe",
      "With lid",
      "Even heat distribution",
    ],
    stockCount: 13,
  },
  {
    id: "21",
    name: "Indigo Hand-Block Printed Shirt",
    subtitle: "Artisan Design",
    category: "kapda",
    price: 2399,
    originalPrice: 2799,
    image: categoryKapda,
    images: [categoryKapda, categoryKapda, categoryKapda],
    description: "Classic indigo hand-block printed shirt with traditional patterns.",
    features: [
      "Hand-block printed",
      "100% cotton",
      "Indigo dyed",
      "Comfortable fit",
    ],
    stockCount: 11,
  },
  {
    id: "22",
    name: "Cold-Pressed Coconut Oil",
    subtitle: "Pure & Natural",
    category: "roti",
    price: 699,
    originalPrice: 799,
    image: categoryRoti,
    images: [categoryRoti, categoryRoti, categoryRoti],
    description: "Cold-pressed virgin coconut oil with natural benefits.",
    features: [
      "Cold-pressed",
      "Virgin quality",
      "Organic",
      "500ml bottle",
    ],
    stockCount: 32,
  },
  {
    id: "23",
    name: "Cane Laundry Basket",
    subtitle: "Eco-Friendly Storage",
    category: "makan",
    price: 2599,
    originalPrice: 2999,
    image: categoryMakan,
    images: [categoryMakan, categoryMakan, categoryMakan],
    description: "Handcrafted cane laundry basket for sustainable living.",
    features: [
      "Natural cane",
      "Eco-friendly",
      "Durable weave",
      "Large capacity",
    ],
    stockCount: 10,
  },
  {
    id: "24",
    name: "Organic Cotton Table Runner",
    subtitle: "Elegant Table Décor",
    category: "kapda",
    price: 1199,
    originalPrice: 1499,
    image: categoryKapda,
    images: [categoryKapda, categoryKapda, categoryKapda],
    description: "Organic cotton table runner with natural weave.",
    features: [
      "100% organic cotton",
      "Natural colors",
      "Machine washable",
      "2m length",
    ],
    stockCount: 19,
  },
  {
    id: "25",
    name: "Ayurvedic Immunity Kadha Mix",
    subtitle: "Wellness Blend",
    category: "roti",
    price: 549,
    originalPrice: null,
    image: categoryRoti,
    images: [categoryRoti, categoryRoti, categoryRoti],
    description: "Traditional ayurvedic immunity-boosting kadha mix.",
    features: [
      "100% organic herbs",
      "Ayurvedic formula",
      "No additives",
      "100g pack",
    ],
    stockCount: 38,
  },
  {
    id: "26",
    name: "Handmade Ceramic Tea Cups",
    subtitle: "Artisan Collection",
    category: "makan",
    price: 1799,
    originalPrice: 2099,
    image: categoryMakan,
    images: [categoryMakan, categoryMakan, categoryMakan],
    description: "Beautiful handmade ceramic tea cups for a warm beverage.",
    features: [
      "Handmade ceramic",
      "Food-safe glaze",
      "Set of 2",
      "Heat-resistant",
    ],
    stockCount: 17,
  },
  {
    id: "27",
    name: "Naturally Dyed Cotton Saree",
    subtitle: "Traditional Elegance",
    category: "kapda",
    price: 3499,
    originalPrice: 3999,
    image: categoryKapda,
    images: [categoryKapda, categoryKapda, categoryKapda],
    description: "Elegant cotton saree with natural plant-based dyes.",
    features: [
      "Naturally dyed",
      "100% cotton",
      "Traditional weave",
      "6 yard length",
    ],
    stockCount: 8,
  },
  {
    id: "28",
    name: "Organic Moringa Powder",
    subtitle: "Nutritional Powerhouse",
    category: "roti",
    price: 499,
    originalPrice: null,
    image: categoryRoti,
    images: [categoryRoti, categoryRoti, categoryRoti],
    description: "Pure organic moringa powder packed with nutrients.",
    features: [
      "100% organic",
      "Nutrient-rich",
      "No additives",
      "100g pack",
    ],
    stockCount: 42,
  },
  {
    id: "29",
    name: "Wooden Spice Box",
    subtitle: "Organized Kitchen",
    category: "makan",
    price: 2299,
    originalPrice: 2699,
    image: categoryMakan,
    images: [categoryMakan, categoryMakan, categoryMakan],
    description: "Traditional wooden spice box for kitchen organization.",
    features: [
      "Solid wood",
      "Multiple compartments",
      "Hand-finished",
      "Compact design",
    ],
    stockCount: 15,
  },
  {
    id: "30",
    name: "Handloom Bath Towel",
    subtitle: "Soft & Absorbent",
    category: "kapda",
    price: 899,
    originalPrice: 1099,
    image: categoryKapda,
    images: [categoryKapda, categoryKapda, categoryKapda],
    description: "Premium handloom cotton bath towel for daily use.",
    features: [
      "100% cotton",
      "Handwoven",
      "Super absorbent",
      "Soft touch",
    ],
    stockCount: 27,
  },
  {
    id: "31",
    name: "Organic Millet Flour Combo",
    subtitle: "Healthy Grains",
    category: "roti",
    price: 799,
    originalPrice: 999,
    image: categoryRoti,
    images: [categoryRoti, categoryRoti, categoryRoti],
    description: "Combo pack of organic millet flours for nutritious cooking.",
    features: [
      "100% organic",
      "Multi-grain combo",
      "Stone-ground",
      "500g pack",
    ],
    stockCount: 36,
  },
  {
    id: "32",
    name: "Terracotta Planter Set",
    subtitle: "Garden Essentials",
    category: "makan",
    price: 1599,
    originalPrice: 1899,
    image: categoryMakan,
    images: [categoryMakan, categoryMakan, categoryMakan],
    description: "Set of terracotta planters for your indoor and outdoor plants.",
    features: [
      "Pure terracotta",
      "Set of 3",
      "Drainage holes",
      "Various sizes",
    ],
    stockCount: 21,
  },
  {
    id: "33",
    name: "Block-Printed Cushion Covers",
    subtitle: "Home Décor",
    category: "kapda",
    price: 1299,
    originalPrice: 1599,
    image: categoryKapda,
    images: [categoryKapda, categoryKapda, categoryKapda],
    description: "Colorful block-printed cotton cushion covers.",
    features: [
      "Hand block-printed",
      "100% cotton",
      "Set of 2",
      "Hidden zip closure",
    ],
    stockCount: 23,
  },
  {
    id: "34",
    name: "Cold-Pressed Groundnut Oil",
    subtitle: "Pure & Healthy",
    category: "roti",
    price: 649,
    originalPrice: 749,
    image: categoryRoti,
    images: [categoryRoti, categoryRoti, categoryRoti],
    description: "Cold-pressed groundnut oil for healthy cooking.",
    features: [
      "Cold-pressed",
      "100% organic",
      "Rich in antioxidants",
      "500ml bottle",
    ],
    stockCount: 34,
  },
  {
    id: "35",
    name: "Handcrafted Wooden Stool",
    subtitle: "Functional Furniture",
    category: "makan",
    price: 2999,
    originalPrice: 3499,
    image: categoryMakan,
    images: [categoryMakan, categoryMakan, categoryMakan],
    description: "Sturdy handcrafted wooden stool for seating and storage.",
    features: [
      "Solid wood",
      "Hand-carved",
      "Durable",
      "Compact size",
    ],
    stockCount: 9,
  },
  {
    id: "36",
    name: "Khadi Cotton Pyjama",
    subtitle: "Comfortable Sleepwear",
    category: "kapda",
    price: 1699,
    originalPrice: 1999,
    image: categoryKapda,
    images: [categoryKapda, categoryKapda, categoryKapda],
    description: "Soft khadi cotton pyjama for comfortable sleep.",
    features: [
      "100% khadi cotton",
      "Handwoven",
      "Breathable",
      "All sizes available",
    ],
    stockCount: 19,
  },
  {
    id: "37",
    name: "Organic Turmeric Powder",
    subtitle: "Golden Spice",
    category: "roti",
    price: 299,
    originalPrice: null,
    image: categoryRoti,
    images: [categoryRoti, categoryRoti, categoryRoti],
    description: "Pure organic turmeric powder with natural benefits.",
    features: [
      "100% organic",
      "High curcumin content",
      "No additives",
      "100g pack",
    ],
    stockCount: 48,
  },
  {
    id: "38",
    name: "Brass Pooja Thali Set",
    subtitle: "Spiritual Essentials",
    category: "makan",
    price: 2499,
    originalPrice: 2899,
    image: categoryMakan,
    images: [categoryMakan, categoryMakan, categoryMakan],
    description: "Traditional brass pooja thali set for rituals.",
    features: [
      "Pure brass",
      "Complete set",
      "Hand-finished",
      "Polished design",
    ],
    stockCount: 12,
  },
  {
    id: "39",
    name: "Handwoven Cotton Shawl",
    subtitle: "Versatile Layer",
    category: "kapda",
    price: 1999,
    originalPrice: 2399,
    image: categoryKapda,
    images: [categoryKapda, categoryKapda, categoryKapda],
    description: "Beautiful handwoven cotton shawl for warmth and style.",
    features: [
      "100% cotton",
      "Handwoven",
      "Lightweight",
      "Elegant design",
    ],
    stockCount: 14,
  },
  {
    id: "40",
    name: "Organic Herbal Digestive Mix",
    subtitle: "Gut Health",
    category: "roti",
    price: 399,
    originalPrice: null,
    image: categoryRoti,
    images: [categoryRoti, categoryRoti, categoryRoti],
    description: "Natural herbal blend for digestive health.",
    features: [
      "100% organic herbs",
      "Ayurvedic formula",
      "No preservatives",
      "100g pack",
    ],
    stockCount: 44,
  },
  {
    id: "41",
    name: "Clay Aroma Diffuser",
    subtitle: "Natural Aromatherapy",
    category: "makan",
    price: 1099,
    originalPrice: 1299,
    image: categoryMakan,
    images: [categoryMakan, categoryMakan, categoryMakan],
    description: "Handcrafted clay aroma diffuser for your home.",
    features: [
      "Pure clay",
      "Hand-molded",
      "Eco-friendly",
      "Aromatherapy ready",
    ],
    stockCount: 25,
  },
  {
    id: "42",
    name: "Handloom Cotton Pillow Cover",
    subtitle: "Comfort & Quality",
    category: "kapda",
    price: 699,
    originalPrice: 899,
    image: categoryKapda,
    images: [categoryKapda, categoryKapda, categoryKapda],
    description: "Soft handloom cotton pillow cover for a good night's sleep.",
    features: [
      "100% cotton",
      "Handwoven",
      "Smooth finish",
      "Zippered closure",
    ],
    stockCount: 30,
  },
  {
    id: "43",
    name: "Organic Raw Peanuts",
    subtitle: "Natural Protein",
    category: "roti",
    price: 249,
    originalPrice: null,
    image: categoryRoti,
    images: [categoryRoti, categoryRoti, categoryRoti],
    description: "Raw organic peanuts for snacking and cooking.",
    features: [
      "100% organic",
      "Raw form",
      "No salt added",
      "250g pack",
    ],
    stockCount: 52,
  },
  {
    id: "44",
    name: "Wooden Wall Shelf",
    subtitle: "Storage & Display",
    category: "makan",
    price: 2799,
    originalPrice: 3199,
    image: categoryMakan,
    images: [categoryMakan, categoryMakan, categoryMakan],
    description: "Elegant wooden wall shelf for displaying and storing items.",
    features: [
      "Solid wood",
      "Hand-finished",
      "Wall-mounted",
      "Durable design",
    ],
    stockCount: 11,
  },
  {
    id: "45",
    name: "Naturally Dyed Cotton Fabric (2m)",
    subtitle: "Raw Material",
    category: "kapda",
    price: 1599,
    originalPrice: 1899,
    image: categoryKapda,
    images: [categoryKapda, categoryKapda, categoryKapda],
    description: "2 meters of naturally dyed cotton fabric for crafts.",
    features: [
      "Naturally dyed",
      "100% cotton",
      "2m length",
      "Eco-friendly",
    ],
    stockCount: 16,
  },
  {
    id: "46",
    name: "Organic Herbal Face Drink",
    subtitle: "Skin Wellness",
    category: "roti",
    price: 599,
    originalPrice: null,
    image: categoryRoti,
    images: [categoryRoti, categoryRoti, categoryRoti],
    description: "Herbal infusion for radiant and healthy skin.",
    features: [
      "100% organic herbs",
      "No additives",
      "Daily drink",
      "100g pack",
    ],
    stockCount: 39,
  },
  {
    id: "47",
    name: "Handcrafted Cane Chair",
    subtitle: "Premium Seating",
    category: "makan",
    price: 6499,
    originalPrice: 7499,
    image: categoryMakan,
    images: [categoryMakan, categoryMakan, categoryMakan],
    description: "Beautifully handcrafted cane chair for comfortable seating.",
    features: [
      "Natural cane",
      "Hand-woven",
      "Ergonomic",
      "Durable frame",
    ],
    stockCount: 6,
  },
  {
    id: "48",
    name: "Khadi Cotton Nehru Jacket",
    subtitle: "Classic Style",
    category: "kapda",
    price: 2999,
    originalPrice: 3499,
    image: categoryKapda,
    images: [categoryKapda, categoryKapda, categoryKapda],
    description: "Traditional khadi cotton Nehru jacket with modern comfort.",
    features: [
      "100% khadi cotton",
      "Handwoven",
      "Formal wear",
      "All sizes available",
    ],
    stockCount: 10,
  },
  {
    id: "49",
    name: "Organic Black Pepper",
    subtitle: "Premium Spice",
    category: "roti",
    price: 399,
    originalPrice: null,
    image: categoryRoti,
    images: [categoryRoti, categoryRoti, categoryRoti],
    description: "Organic black pepper with natural flavor and aroma.",
    features: [
      "100% organic",
      "Whole peppercorns",
      "Fresh aroma",
      "100g pack",
    ],
    stockCount: 46,
  },
  {
    id: "50",
    name: "Brass Door Handle Pair",
    subtitle: "Hardware Accent",
    category: "makan",
    price: 1899,
    originalPrice: 2199,
    image: categoryMakan,
    images: [categoryMakan, categoryMakan, categoryMakan],
    description: "Traditional brass door handle pair for your home.",
    features: [
      "Pure brass",
      "Hand-finished",
      "Pair of 2",
      "Traditional design",
    ],
    stockCount: 13,
  },
  {
    id: "51",
    name: "Handwoven Cotton Floor Mat",
    subtitle: "Home Essential",
    category: "kapda",
    price: 1399,
    originalPrice: 1699,
    image: categoryKapda,
    images: [categoryKapda, categoryKapda, categoryKapda],
    description: "Durable handwoven cotton floor mat for any room.",
    features: [
      "100% cotton",
      "Handwoven",
      "Machine washable",
      "Non-slip backing",
    ],
    stockCount: 18,
  },
  {
    id: "52",
    name: "Organic Lemon Pickle",
    subtitle: "Tangy Condiment",
    category: "roti",
    price: 299,
    originalPrice: null,
    image: categoryRoti,
    images: [categoryRoti, categoryRoti, categoryRoti],
    description: "Homemade style organic lemon pickle with traditional recipe.",
    features: [
      "100% organic",
      "No preservatives",
      "Traditional recipe",
      "200g jar",
    ],
    stockCount: 49,
  },
  {
    id: "53",
    name: "Clay Storage Jars Set",
    subtitle: "Kitchen Storage",
    category: "makan",
    price: 2199,
    originalPrice: 2599,
    image: categoryMakan,
    images: [categoryMakan, categoryMakan, categoryMakan],
    description: "Set of handmade clay storage jars for kitchen staples.",
    features: [
      "Pure clay",
      "Set of 3",
      "Food-safe glaze",
      "Various sizes",
    ],
    stockCount: 14,
  },
  {
    id: "54",
    name: "Handloom Cotton Kitchen Towels",
    subtitle: "Daily Essential",
    category: "kapda",
    price: 799,
    originalPrice: 999,
    image: categoryKapda,
    images: [categoryKapda, categoryKapda, categoryKapda],
    description: "Soft handloom cotton kitchen towels for everyday use.",
    features: [
      "100% cotton",
      "Handwoven",
      "Set of 2",
      "Absorbent",
    ],
    stockCount: 31,
  },
  {
    id: "55",
    name: "Organic Tulsi Powder",
    subtitle: "Immunity Booster",
    category: "roti",
    price: 349,
    originalPrice: null,
    image: categoryRoti,
    images: [categoryRoti, categoryRoti, categoryRoti],
    description: "Pure organic tulsi powder for health and wellness.",
    features: [
      "100% organic tulsi",
      "No additives",
      "High antioxidants",
      "100g pack",
    ],
    stockCount: 47,
  },
  {
    id: "56",
    name: "Wooden Bedside Table",
    subtitle: "Bedroom Furniture",
    category: "makan",
    price: 4499,
    originalPrice: 4999,
    image: categoryMakan,
    images: [categoryMakan, categoryMakan, categoryMakan],
    description: "Handcrafted wooden bedside table with elegant design.",
    features: [
      "Solid wood",
      "Hand-finished",
      "Drawer storage",
      "Classic design",
    ],
    stockCount: 7,
  },
  {
    id: "57",
    name: "Naturally Dyed Cotton Kurti",
    subtitle: "Casual Comfort",
    category: "kapda",
    price: 1899,
    originalPrice: 2199,
    image: categoryKapda,
    images: [categoryKapda, categoryKapda, categoryKapda],
    description: "Comfortable cotton kurti with natural plant-based dyes.",
    features: [
      "Naturally dyed",
      "100% cotton",
      "Relaxed fit",
      "Easy care",
    ],
    stockCount: 17,
  },
  {
    id: "58",
    name: "Organic Dry Fruit Mix",
    subtitle: "Healthy Snacking",
    category: "roti",
    price: 899,
    originalPrice: 1099,
    image: categoryRoti,
    images: [categoryRoti, categoryRoti, categoryRoti],
    description: "Mixed organic dry fruits for nutritious snacking.",
    features: [
      "100% organic",
      "No added sugar",
      "Assorted mix",
      "200g pack",
    ],
    stockCount: 41,
  },
  {
    id: "59",
    name: "Handcrafted Wooden Photo Frame",
    subtitle: "Memory Display",
    category: "makan",
    price: 999,
    originalPrice: 1199,
    image: categoryMakan,
    images: [categoryMakan, categoryMakan, categoryMakan],
    description: "Beautiful wooden photo frame for displaying cherished memories.",
    features: [
      "Solid wood",
      "Hand-carved",
      "Glass front",
      "Easel back",
    ],
    stockCount: 22,
  },
  {
    id: "60",
    name: "Handloom Cotton Yoga Mat Cover",
    subtitle: "Fitness Accessory",
    category: "kapda",
    price: 1099,
    originalPrice: 1399,
    image: categoryKapda,
    images: [categoryKapda, categoryKapda, categoryKapda],
    description: "Handwoven cotton yoga mat cover for easy transport.",
    features: [
      "100% cotton",
      "Handwoven",
      "Carrying strap",
      "Machine washable",
    ],
    stockCount: 21,
  },
  {
    id: "61",
    name: "Organic Ginger Powder",
    subtitle: "Warming Spice",
    category: "roti",
    price: 299,
    originalPrice: null,
    image: categoryRoti,
    images: [categoryRoti, categoryRoti, categoryRoti],
    description: "Pure organic ginger powder with natural warmth.",
    features: [
      "100% organic",
      "Freshly ground",
      "No additives",
      "100g pack",
    ],
    stockCount: 51,
  },
  {
    id: "62",
    name: "Terracotta Oil Lamp Set",
    subtitle: "Traditional Lighting",
    category: "makan",
    price: 899,
    originalPrice: null,
    image: categoryMakan,
    images: [categoryMakan, categoryMakan, categoryMakan],
    description: "Set of traditional terracotta oil lamps for festivals.",
    features: [
      "Pure terracotta",
      "Set of 4",
      "Hand-molded",
      "Traditional design",
    ],
    stockCount: 28,
  },
  {
    id: "63",
    name: "Khadi Cotton Lounge Pants",
    subtitle: "Comfortable Wear",
    category: "kapda",
    price: 1799,
    originalPrice: 2099,
    image: categoryKapda,
    images: [categoryKapda, categoryKapda, categoryKapda],
    description: "Soft khadi cotton lounge pants for relaxation.",
    features: [
      "100% khadi cotton",
      "Handwoven",
      "Comfortable fit",
      "All sizes available",
    ],
    stockCount: 15,
  },
  {
    id: "64",
    name: "Organic Herbal Green Tea",
    subtitle: "Wellness Brew",
    category: "roti",
    price: 499,
    originalPrice: null,
    image: categoryRoti,
    images: [categoryRoti, categoryRoti, categoryRoti],
    description: "Organic herbal green tea blend for health and vitality.",
    features: [
      "100% organic",
      "Green tea base",
      "No caffeine",
      "50g pack",
    ],
    stockCount: 43,
  },
  {
    id: "65",
    name: "Handcrafted Wooden Serving Bowl",
    subtitle: "Kitchen Essential",
    category: "makan",
    price: 1599,
    originalPrice: 1899,
    image: categoryMakan,
    images: [categoryMakan, categoryMakan, categoryMakan],
    description: "Wooden serving bowl handcrafted for daily use.",
    features: [
      "Solid wood",
      "Hand-turned",
      "Food-safe finish",
      "Durable design",
    ],
    stockCount: 16,
  },
  {
    id: "66",
    name: "Handloom Cotton Curtain Panel",
    subtitle: "Home Décor",
    category: "kapda",
    price: 2499,
    originalPrice: 2899,
    image: categoryKapda,
    images: [categoryKapda, categoryKapda, categoryKapda],
    description: "Elegant handloom cotton curtain panel for your windows.",
    features: [
      "100% cotton",
      "Handwoven",
      "Rod pocket",
      "Easy care",
    ],
    stockCount: 12,
  },
  {
    id: "67",
    name: "Organic Raw Honey with Tulsi",
    subtitle: "Pure Wellness",
    category: "roti",
    price: 699,
    originalPrice: null,
    image: categoryRoti,
    images: [categoryRoti, categoryRoti, categoryRoti],
    description: "Raw honey infused with organic tulsi for immunity.",
    features: [
      "Raw honey",
      "Tulsi-infused",
      "100% organic",
      "250g jar",
    ],
    stockCount: 40,
  },
  {
    id: "68",
    name: "Clay Handwash Dispenser",
    subtitle: "Eco-Friendly Bath",
    category: "makan",
    price: 1299,
    originalPrice: 1499,
    image: categoryMakan,
    images: [categoryMakan, categoryMakan, categoryMakan],
    description: "Handmade clay handwash dispenser for your bathroom.",
    features: [
      "Pure clay",
      "Hand-molded",
      "Eco-friendly",
      "Pump mechanism",
    ],
    stockCount: 20,
  },
  {
    id: "69",
    name: "Naturally Dyed Cotton Cushion",
    subtitle: "Soft Comfort",
    category: "kapda",
    price: 1399,
    originalPrice: 1699,
    image: categoryKapda,
    images: [categoryKapda, categoryKapda, categoryKapda],
    description: "Naturally dyed cotton cushion with beautiful colors.",
    features: [
      "Naturally dyed",
      "100% cotton",
      "Soft filling",
      "Hand-stitched",
    ],
    stockCount: 19,
  },
  {
    id: "70",
    name: "Organic Cinnamon Powder",
    subtitle: "Aromatic Spice",
    category: "roti",
    price: 349,
    originalPrice: null,
    image: categoryRoti,
    images: [categoryRoti, categoryRoti, categoryRoti],
    description: "Pure organic cinnamon powder with rich aroma.",
    features: [
      "100% organic",
      "Freshly ground",
      "Natural sweetness",
      "100g pack",
    ],
    stockCount: 48,
  },
  {
    id: "71",
    name: "Handcrafted Wooden Key Holder",
    subtitle: "Organizational Tool",
    category: "makan",
    price: 899,
    originalPrice: null,
    image: categoryMakan,
    images: [categoryMakan, categoryMakan, categoryMakan],
    description: "Charming wooden key holder for organizing your keys.",
    features: [
      "Solid wood",
      "Hand-carved",
      "Wall-mounted",
      "Compact design",
    ],
    stockCount: 26,
  },
  {
    id: "72",
    name: "Handloom Cotton Apron",
    subtitle: "Kitchen Wear",
    category: "kapda",
    price: 999,
    originalPrice: 1199,
    image: categoryKapda,
    images: [categoryKapda, categoryKapda, categoryKapda],
    description: "Handwoven cotton apron for cooking and baking.",
    features: [
      "100% cotton",
      "Handwoven",
      "Multiple pockets",
      "Adjustable straps",
    ],
    stockCount: 24,
  },
  {
    id: "73",
    name: "Organic Herbal Detox Drink",
    subtitle: "Cleansing Brew",
    category: "roti",
    price: 599,
    originalPrice: null,
    image: categoryRoti,
    images: [categoryRoti, categoryRoti, categoryRoti],
    description: "Herbal detox drink blend for natural cleansing.",
    features: [
      "100% organic herbs",
      "No additives",
      "Daily wellness",
      "100g pack",
    ],
    stockCount: 37,
  },
  {
    id: "74",
    name: "Terracotta Soap Dish",
    subtitle: "Bath Accessory",
    category: "makan",
    price: 499,
    originalPrice: null,
    image: categoryMakan,
    images: [categoryMakan, categoryMakan, categoryMakan],
    description: "Natural terracotta soap dish for your bathroom.",
    features: [
      "Pure terracotta",
      "Hand-molded",
      "Drainage holes",
      "Eco-friendly",
    ],
    stockCount: 29,
  },
  {
    id: "75",
    name: "Khadi Cotton Shirt",
    subtitle: "Casual Elegance",
    category: "kapda",
    price: 2199,
    originalPrice: 2499,
    image: categoryKapda,
    images: [categoryKapda, categoryKapda, categoryKapda],
    description: "Classic khadi cotton shirt for everyday wear.",
    features: [
      "100% khadi cotton",
      "Handwoven",
      "Comfortable fit",
      "All sizes available",
    ],
    stockCount: 13,
  },
  {
    id: "76",
    name: "Organic Raw Sugar",
    subtitle: "Natural Sweetener",
    category: "roti",
    price: 299,
    originalPrice: null,
    image: categoryRoti,
    images: [categoryRoti, categoryRoti, categoryRoti],
    description: "Organic raw sugar for natural sweetening.",
    features: [
      "100% organic",
      "No processing",
      "Natural crystals",
      "250g pack",
    ],
    stockCount: 50,
  },
  {
    id: "77",
    name: "Wooden Cutlery Organizer",
    subtitle: "Kitchen Organization",
    category: "makan",
    price: 1499,
    originalPrice: 1799,
    image: categoryMakan,
    images: [categoryMakan, categoryMakan, categoryMakan],
    description: "Wooden organizer for keeping cutlery neat and tidy.",
    features: [
      "Solid wood",
      "Multiple compartments",
      "Hand-finished",
      "Compact design",
    ],
    stockCount: 18,
  },
  {
    id: "78",
    name: "Handloom Cotton Table Cloth",
    subtitle: "Table Elegance",
    category: "kapda",
    price: 1999,
    originalPrice: 2299,
    image: categoryKapda,
    images: [categoryKapda, categoryKapda, categoryKapda],
    description: "Beautiful handloom cotton tablecloth for dining.",
    features: [
      "100% cotton",
      "Handwoven",
      "Machine washable",
      "Various sizes",
    ],
    stockCount: 14,
  },
  {
    id: "79",
    name: "Organic Herbal Chyawanprash",
    subtitle: "Immunity Tonic",
    category: "roti",
    price: 499,
    originalPrice: null,
    image: categoryRoti,
    images: [categoryRoti, categoryRoti, categoryRoti],
    description: "Traditional organic chyawanprash for immunity and vitality.",
    features: [
      "100% organic herbs",
      "Ayurvedic formula",
      "No preservatives",
      "200g jar",
    ],
    stockCount: 45,
  },
  {
    id: "80",
    name: "Handcrafted Wooden Tissue Holder",
    subtitle: "Bathroom Essential",
    category: "makan",
    price: 1199,
    originalPrice: 1399,
    image: categoryMakan,
    images: [categoryMakan, categoryMakan, categoryMakan],
    description: "Handcrafted wooden tissue holder for your home.",
    features: [
      "Solid wood",
      "Hand-carved",
      "Wall or counter mount",
      "Space-saving design",
    ],
    stockCount: 23,
  },
];